// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Yaaf.Xmpp.Runtime")]
[assembly: AssemblyProductAttribute("Yaaf.Xmpp.Runtime")]
[assembly: AssemblyCopyrightAttribute("Yaaf.Xmpp.Runtime Copyright © Matthias Dittrich 2015")]
[assembly: AssemblyVersionAttribute("0.0.4")]
[assembly: AssemblyFileVersionAttribute("0.0.4")]
[assembly: AssemblyInformationalVersionAttribute("0.0.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.4";
    }
}
