// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Yaaf")]
[assembly: AssemblyProductAttribute("Yaaf.Xmpp")]
[assembly: AssemblyCopyrightAttribute("Matthias Dittrich � 2014")]
[assembly: AssemblyVersionAttribute("2014.04.02.00")]
[assembly: AssemblyFileVersionAttribute("2014.04.02.00")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2014.04.02.00";
    }
}
